<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="../public/css/sliders.css">
    <link rel="stylesheet" type="text/css" href="../public/css/tables.css">

    <style>
        .error {color: #FF0000;}
    </style>
</head>
<body>

<?php

echo "<h1>Hello! -udpated</h1>";

echo "<img src=../public/img/a-and-b-gpio-numbers_u9sxw0.png>";
echo PHP_EOL;

echo PHP_EOL;


$status = array ( 0 );
//set pins mode to output

system ( "sudo gpio mode 2 out" );

for ($i = 0; $i <= 7; $i++ )
{
    //turns on the LEDs
    system("sudo gpio write 2 1");

    //reads and prints the LEDs statuse
    exec("sudo gpio read 2", $status);
    echo($status[0]);

    //waits 2 seconds
    sleep(1);

    //turns off the LEDs
    system("sudo gpio write 2 0");
    sleep(1);
}

echo $this->tag->linkTo(
    "sprinkla",
    "Control the sprinklas"
);